### PR TITLE
Automatic reformatting using clang-format-3.8 and style=google

### PR DESCRIPTION
**Pull request by wxmerkt**
Proposal to address #131 

- Command used: ``find -name '*.cpp' -o -name '*.h' | xargs clang-format-3.8 -style=google -i``, committed under neutral author Exotica Dev Team
- On top of a hotfix required for it to work: https://github.com/ipab-slmc/exotica/commit/18254951cd523eeb7c9e453b5ea690df36a1bcf6
- Will add an automatic pre-commit-hook that runs ``clang-format-3.8`` before any commit in a follow-up PR (i.e. with clang-format install no further user action required)

### CODE REVIEW

**Comment by wxmerkt** [comment]
@VladimirIvan I went through the code and the line-breaking seems okay. Where it's really annoying or we prefer not to wrap or do our own indentation for whatever reason we can either end that line with ``// clang-format off`` or encapsulate a block by ``// clang-format off`` and ``// clang-format on``. I've added an example of where this made a difference to keep the original indentation (exotica_examples/src/generic.cpp). Overall, I think the formatter gives better readability with the automatic wrapping even if it's sometimes a bit too aggressive for some lines, where we can then control manually. 80 seems like a fine limit for having 2 documents next to each other on a landscape widescreen or a single file on a portrait-oriented screen. Additionally, it makes a lot of sense when comparing changes e.g. here on GitHub during reviews where we have two files side by side. Happy to revert/fix any blocks in the changes that it was too aggressive, but generally probably better if we stick to the standard.

**Comment by VladimirIvan** [comment]
Here are a couple of examples where the 80 character line break is just plain silly:
```
 static std::shared_ptr<fcl::CollisionObjectd> constructFclCollisionObject(
     std::shared_ptr<KinematicElement> element);
 static void checkCollision(fcl::CollisionObjectd* o1,
                            fcl::CollisionObjectd* o2, CollisionData* data);
 static void computeDistance(fcl::CollisionObjectd* o1,
                             fcl::CollisionObjectd* o2, DistanceData* data);
 if (info != 0) {
   throw_pretty("Can't invert matrix. Cholesky decomposition failed: " << info
                                                                        << "\n"
                                                                        << A_);
 }
```
Adding a formatting exception before each of those is just too much.

I'm having my doubts about the google style as well:
```
 if (J.cols() < J.rows()) {
   //(Jt*C^-1*J+W)^-1*Jt*C^-1
   if (parameters_.C != 0) {
     Jpinv =
         inverseSymPosDef(J.transpose() * Cinv * J + W) * J.transpose() * Cinv;
   } else {
     Jpinv = inverseSymPosDef(J.transpose() * J + W) * J.transpose();
   }
 } else {
   // W^-1*Jt(J*W^-1*Jt+C)
   Jpinv =
       Winv * J.transpose() * inverseSymPosDef(J * Winv * J.transpose() + C);
 }
```
Having just two spaces for indentation makes it really hard to see where block belong to in longer statements. I literally have to stop reading the code after every line. Below is what the original was intended to look like:
```
if (J.cols() < J.rows()) 
{
    //(Jt*C^-1*J+W)^-1*Jt*C^-1
    if (parameters_.C != 0) 
    {
        Jpinv = inverseSymPosDef(J.transpose() * Cinv * J + W) * J.transpose() * Cinv;
    } 
    else 
    {
        Jpinv = inverseSymPosDef(J.transpose() * J + W) * J.transpose();
    }
} 
else 
{
    // W^-1*Jt(J*W^-1*Jt+C)
    Jpinv = Winv * J.transpose() * inverseSymPosDef(J * Winv * J.transpose() + C);
}
```

I'm no longer convinced google style is the right way to go at all. I'll keep looking for a solution.

**Comment by VladimirIvan** [comment]
Actually, Google with these three changes is fine:
```
IndentWidth: 4
ColumnLimit: 500
BreakBeforeBraces: Allman
```

**Comment by wxmerkt** [comment]
Added config file and updated this PR. The command can be run from the root of the repository with ``find -name '*.cpp' -o -name '*.h' | xargs clang-format-3.8 -style=.clang-format -i``.

**I still think we should think about a sensible column limit. Our merge tools - both GitHub and meld - are pretty poor with inline changes over long lines so reviewing and merging changes will become more difficult with this high of a limit. Open for any suggestions but the shorter the better for both GitHub reviews as well as manual merges.**

**Pull request merged**
