### PR TITLE
Cross-platform CI with conda packages

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Hi @wxmerkt,

This should save you from setting up Docker stuff. It runs a build using dependencies from conda-forge and other ROS packages build in RoboStack (https://github.com/RoboStack/ros-noetic). Feel free to play around to see whether you can find the Eigen issue. It would be really nice to see this PR merged :).

We have a similar PR in rviz: https://github.com/ros-visualization/rviz/pull/1600

/cc @wolfv

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
You can also easily setup a conda test locally for faster iterations - see https://github.com/RoboStack/ros-noetic/blob/master/CONTRIBUTING.md

When the build fails, the last line will be a command that you can run to go into the build environment for even faster iterations.

**Comment by Tobias-Fischer** [comment]
GitHub actions in action: https://github.com/Tobias-Fischer/exotica/actions

**Comment by wxmerkt** [comment]
Fantastic, thank you! I was just looking at the RViz CI example :-D Ignore the latest comment in #737 please while I work with this branch :-).

**Comment by Tobias-Fischer** [comment]
Oh wow, that was a quick merge - thanks!
I noticed that you probably need to set `fail-fast: false` - I should have tested Windows+OSX as well; I guess for now let's focus on the Linux build.

**Comment by wxmerkt** [comment]
Thanks - I commented Windows & Mac OS X for now to debug the Eigen issue and will then successively check how involved it would be to enable Mac OS X and potentially Windows. I'll keep you posted :)

**Pull request merged**
