### PR TITLE
Point2Line test added and initialisation fix

### PR DESCRIPTION
**Pull request by wxmerkt**
Hi @christian-rauch,
Can you please have a look at whether this works?

Cheers,
Wolf

### CODE REVIEW

**Comment by wxmerkt** [comment]
@christian-rauch Can you please add an example of the XML you are using with this task map? Changing the frame causes an error in the Jacobian (see newly added commit).

**Comment by christian-rauch** [comment]
I am using the following code snipped in Python to define my P2L task maps:

```python
# setup
(self.sol_conf, self.prob_conf) = exo.Initializers.loadXMLFull(conf)
self.solver = exo.Setup.createSolver(self.sol_conf)
self.problem = exo.Setup.createProblem(self.prob_conf)
self.solver.specifyProblem(self.problem)

# formatting of parameter (link_name, line_cam, pnt_lnk, line_length)
problem_conf = self.prob_conf[1]
base_frame = "world"
point_fmt = (" ").join(pnt_lnk.astype(str).tolist())  # point in link frame
line_start_fmt = (" ").join(line_cam.astype(str).tolist())  # line start in camera frame
line_end = (line_cam/np.linalg.norm(line_cam)) * line_length
line_end_fmt = (" ").join(line_end.astype(str).tolist())  # line end in camera frame
infinite = False
infinite_fmt = str(infinite)

# problem definition
frame_conf = {'Link': link_name, 'LinkOffset': point_fmt,
              'Base': base_frame, 'BaseOffset': line_start_fmt}
task_name = "P2L_" + link_name
problem_conf['Maps'].append(("exotica/Point2Line", {"EndEffector": [("exotica/Frame", frame_conf)], 'Name': task_name, 'EndPoint': line_end_fmt, 'infinite': infinite_fmt, 'Debug':'0'}))
problem_conf['Cost'].append(('exotica/Task', {'Task': task_name, 'Rho': str(weight)}))
 self.prob_conf = (self.prob_conf[0], problem_conf)
```
 `link_name` is the tip link i.e. the link in which the point `pnt_lnk` is given. `base_frame` is the frame in which the line with direction from `line_cam` to `line_end` is defined. `line_end` is hereby interpreted as direction (infinite) or end of the line segment (finite).

**Comment by christian-rauch** [comment]
I had a further look at the tests and the Jacobian from the P2L task map and the one computed in the test. The Jacobians from the P2L task map seem stable, i.e. the differences are in the range of 1e-5.

**Comment by christian-rauch** [comment]
I haven't figures out yet, what is wrong with the `Point2Line` Jacobian compared to the numerical Jacobian from the test. For now I "fixed" the test by setting the line start and end to the same point, which effectively reduces the task map to the `Distance` task map.

**Comment by wxmerkt** [comment]
Closing as will be superseded by and included in #339.

**Pull request closed without merging**
