### PR TITLE
[exotica_levenberg_marquardt_solver] Use colPivHouseholderQr if Eigen < 3.3.0 (fix 16.04 bug)

### PR DESCRIPTION
**Pull request by wxmerkt**
As reported in #453: As we are not building the Levenberg-Marquardt solver on 16.04 _but_ maintain a `exotica_plugins.xml` file, `pyexotica` won't run any example. We have two solutions hereto (provide newer Eigen, or create the plugin-export file during configuration). This PR _may_ fix this issue but I do not have a way to test right now as I am on 16.04 over the holidays.

### CODE REVIEW

**Comment by wxmerkt** [comment]
This "fix" throws warnings though marked as error:
```
Skipped loading plugin with error: XML Document '/home/wxm/dev/exotica_ws/src/exotica/exotations/solvers/exotica_levenberg_marquardt_solver/exotica_plugins.xml' has no Root Element. This likely means the XML is malformed or missing..
```

**Comment by VladimirIvan** [comment]
Can you either:
 A. Include only `CompleteOrthogonalDecomposition.h` from a newer Eigen? (copy/paste/include into src)
or
 B. Use a linear system solver base on a different decomposition (SVD, LU, ...)?

**Comment by wxmerkt** [comment]
Option (A) does not work.

I have now added a compile-time macro to select the linear solver. On 16.04, we will use `colPivHouseholderQr` while opting for `completeOrthogonalDecomposition` if the Eigen version is recent enough. Please feel free to suggest [other linear solvers](https://eigen.tuxfamily.org/dox/group__TutorialLinearAlgebra.html).

@christian-rauch Can you please have a look over? Thanks!

**Comment by christian-rauch** [comment]
The main reason I selected `CompleteOrthogonalDecomposition` as solver was that for matrices with bad condition numbers, the alternative solvers (LDLT, LLT) produced unstable results (different results for the same input).

But from the comparison table in the Eigen documentation, it looks as if `CompleteOrthogonalDecomposition` and `ColPivHouseholderQR` have the same properties. So this would be fine by me.

The `example_levenbergmarquardt.xml` is using the `LevenbergMarquardtSolver` in its default configuration, which then behaves like the Gauss-Newton. You could add the damping parameter for demonstration purpose. Thanks for putting together the LM example @wxmerkt

**Pull request merged**
