### PR TITLE
Various Fixes/Issues

### LINKED ISSUE #654: DDP, iLQG solvers return wrong-sized solution
If the problem horizon is `T`, then:

- `X` is of size `T`
- `U` is of size `T-1`
- The `solution` in `Solve` in the solvers is **resized** to `T` without initialising or reinitialising to 0. At the end of solve, only the T-1th rows are getting set from the best U. That returns an additional row with a wrongly initialised memory.

Two possible solutions:
a) The returned solution should be of size `T-1`
b) The final command should be a hold/inverse dynamics solution or zeros. 

I tend to (a).

### PR DESCRIPTION
**Pull request by include4eto**
- https://github.com/ipab-slmc/exotica/issues/654
- https://github.com/ipab-slmc/exotica/issues/653
- https://github.com/ipab-slmc/exotica/issues/632
- https://github.com/ipab-slmc/exotica/issues/613

Fixes #654, #653, #632, #613

=> Not yet ready for merging, just preview

### CODE REVIEW

**Comment by include4eto** [comment]
Fixes #654, #653, #632, #613

**Comment by wxmerkt** [comment]
I've added that to the first post - subsequent comments won't be parsed. Also if you use # in your commit message it directly links to the issue from the commit :-)

**Comment by wxmerkt** [comment]
@include4eto what is missing for this to be able to get merged?

**Comment by include4eto** [comment]
> @include4eto what is missing for this to be able to get merged?

I originally wanted to fix all issues regarding dynamics solver. However, it seems that might be a little ways down the road atm. Will fix the build issues ASAP so we can merge.

**Comment by include4eto** [comment]
Should be OK to merge now. Just waiting for the build to finish,

**Pull request merged**
