### PR TITLE
Add Dubin'ss state-space support for OMPL solvers

### LINKED ISSUE #701: Support for differential drive robots
Currently, it is possible to plan with floating bases. Libraries like OMPL also support differential drives, using DubinsStateSpaces or ReedsSheppStateSpaces. Integrating this feature would allow planning for a new range of robots, mainly autonomous cars and mobile manipulators.

### PR DESCRIPTION
**Pull request by maxspahn**
Implementation of dubinStateSpace for exotica.
Compilation works but the execution does not run with test case "example_ompl_freebase.xml".

It still needs parameterization.

Resolves #701.

### CODE REVIEW

**Comment by wxmerkt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- exotations/solvers/exotica_ompl_solver/include/exotica_ompl_solver/ompl_exo.h  5
- exotations/solvers/exotica_ompl_solver/src/ompl_exo.cpp  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ipab-slmc/exotica/pullRequest?prid=5407071&bid=17726770)

**Comment by wxmerkt** [comment]
Thanks for the PR! I figured out the issue and will upload a fix to the branch soon.

ompl_dubins

**Comment by maxspahn** [comment]
I am looking forward to the fix! Looks exactly as what I have expected.

**Comment by wxmerkt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- exotations/solvers/exotica_ompl_solver/include/exotica_ompl_solver/ompl_exo.h  5
- exotations/solvers/exotica_ompl_solver/src/ompl_exo.cpp  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ipab-slmc/exotica/pullRequest?prid=5407071&bid=17726770)

**Comment by wxmerkt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- exotations/solvers/exotica_ompl_solver/include/exotica_ompl_solver/ompl_exo.h  5
- exotations/solvers/exotica_ompl_solver/src/ompl_exo.cpp  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ipab-slmc/exotica/pullRequest?prid=5407071&bid=17726770)

**Comment by wxmerkt** [comment]
I've pushed the fixes to this PR and made the option to activate Dubin or regular SE(2) planning space an initializer parameter. There is now also an example.

**Pull request merged**
